[2023-07-10T11:54:38.059+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.merge_sources manual__2023-07-10T11:54:22.994124+00:00 [queued]>
[2023-07-10T11:54:38.074+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.merge_sources manual__2023-07-10T11:54:22.994124+00:00 [queued]>
[2023-07-10T11:54:38.075+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T11:54:38.103+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): merge_sources> on 2023-07-10 11:54:22.994124+00:00
[2023-07-10T11:54:38.113+0000] {standard_task_runner.py:57} INFO - Started process 634 to run task
[2023-07-10T11:54:38.120+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'merge_sources', 'manual__2023-07-10T11:54:22.994124+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmp82pi4m3h']
[2023-07-10T11:54:38.121+0000] {standard_task_runner.py:85} INFO - Job 193: Subtask merge_sources
[2023-07-10T11:54:38.197+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.merge_sources manual__2023-07-10T11:54:22.994124+00:00 [running]> on host 6998c1ab8829
[2023-07-10T11:54:38.360+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='merge_sources' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T11:54:22.994124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T11:54:22.994124+00:00'
[2023-07-10T11:54:38.462+0000] {python.py:183} INFO - Done. Returned value was:      age sex on_thyroxine  ... TBG referral_source     Class
0     41   F            f  ...   ?            SVHC  negative
1     23   F            f  ...   ?           other  negative
2     46   M            f  ...   ?           other  negative
3     70   F            t  ...   ?           other  negative
4     70   F            f  ...   ?             SVI  negative
...   ..  ..          ...  ...  ..             ...       ...
3767  30   F            f  ...   ?           other  negative
3768  68   F            f  ...   ?             SVI  negative
3769  74   F            f  ...   ?           other  negative
3770  72   M            f  ...   ?             SVI  negative
3771  64   F            f  ...   ?           other  negative

[3772 rows x 30 columns]
[2023-07-10T11:54:38.548+0000] {xcom.py:640} ERROR - ("Could not convert '77' with type str: tried to convert to int64", 'Conversion failed for column age with type object'). If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-07-10T11:54:38.552+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2361, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 243, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 142, in serialize
    data, classname, version, is_serialized = _serializers[qn].serialize(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serializers/pandas.py", line 49, in serialize
    table = pa.Table.from_pandas(o)
  File "pyarrow/table.pxi", line 3557, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 624, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert '77' with type str: tried to convert to int64", 'Conversion failed for column age with type object')
[2023-07-10T11:54:38.576+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=merge_sources, execution_date=20230710T115422, start_date=20230710T115438, end_date=20230710T115438
[2023-07-10T11:54:38.603+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 193 for task merge_sources (("Could not convert '77' with type str: tried to convert to int64", 'Conversion failed for column age with type object'); 634)
[2023-07-10T11:54:38.658+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T11:54:38.708+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
