[2023-07-12T13:26:56.192+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.transform_ordinal_train manual__2023-07-12T13:25:40.792504+00:00 [queued]>
[2023-07-12T13:26:56.218+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.transform_ordinal_train manual__2023-07-12T13:25:40.792504+00:00 [queued]>
[2023-07-12T13:26:56.219+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-12T13:26:56.257+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transform_ordinal_train> on 2023-07-12 13:25:40.792504+00:00
[2023-07-12T13:26:56.272+0000] {standard_task_runner.py:57} INFO - Started process 3993 to run task
[2023-07-12T13:26:56.285+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'transform_ordinal_train', 'manual__2023-07-12T13:25:40.792504+00:00', '--job-id', '765', '--raw', '--subdir', 'DAGS_FOLDER/dagfile.py', '--cfg-path', '/tmp/tmpa1e14bam']
[2023-07-12T13:26:56.287+0000] {standard_task_runner.py:85} INFO - Job 765: Subtask transform_ordinal_train
[2023-07-12T13:26:56.422+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.transform_ordinal_train manual__2023-07-12T13:25:40.792504+00:00 [running]> on host 93aa310e5d41
[2023-07-12T13:26:56.616+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='transform_ordinal_train' AIRFLOW_CTX_EXECUTION_DATE='2023-07-12T13:25:40.792504+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-12T13:25:40.792504+00:00'
[2023-07-12T13:26:56.643+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/scalers.py", line 35, in transform_ordinal_train
    with open(ordinal_scaler_path, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-07-12T13:26:56.666+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=transform_ordinal_train, execution_date=20230712T132540, start_date=20230712T132656, end_date=20230712T132656
[2023-07-12T13:26:56.692+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 765 for task transform_ordinal_train (expected str, bytes or os.PathLike object, not NoneType; 3993)
[2023-07-12T13:26:56.739+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-12T13:26:56.783+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
